### ISSUE TITLE
overrepresented barcodes by lane

### ISSUE THREAD

**Issue by VAIgenomics** [vari-bbc/demultiplex#11] opened 2021-06-23 15:41 UTC
I was curious if we could add this feature to the bcl2fastq_snake.sh, typically with the bcl2fast script text files are generated in the diagnostic files folder like:

Barcodes_fraction_greater_than_0.0005_L001

These are really helpful when we are trying to identify index mix ups or issues. I noticed the pipeline doesn't currently do this. It is not a high priority issue, but would be helpful in the future.

**Comment by genomics-kl** [comment] 2021-06-23 16:24
@VAIgenomics , this seems to be caused one of the recent changes to the pipeline. This functionality was never removed intentionally. Looking into it now.

**Comment by genomics-kl** [comment] 2021-06-23 16:30
@heyyyjude , the issue seems to be due to the absence of the 'Data/Intensities/BaseCalls/Undetermined_L000_R1/2_001.fastq.gz' file. This file is typically produced by rule 'cat_fqs_undetermined'. I think that because FastQC and Fastq_Screen are no longer run on these files,  rule 'cat_fqs_undetermined' is not run at all. We can fix this by putting the file as input for rule 'all'. 

After that, you can run the pipeline with the most recent commit and, separately, run it using a commit before the recent changes to make sure that no other files are removed except the FastQC and Fastq_Screen outputs for the Undetermined fastqs.

**Comment by heyyyjude** [comment] 2021-06-23 16:35
@genomics-kl Thank you for your explnation. I will work on it.

**Comment by genomics-kl** [comment] 2021-06-23 16:54
@heyyyjude Part of the problem is that some of the code in 'bcl2fastq.sh' were not migrated to Snakemake but simply copied to 'bcl2fastq_snake.sh'. The missing file in question is one of the outputs of that 'legacy' code.

It's up to you if you want to convert those to Snakemake. It may make it easier to maintain.

**Comment by heyyyjude** [comment] 2021-06-25 16:37
@genomics-kl 
Hi Kin. I did what you had explained and I think I had the right outputs. I just confirmed that the cat_fq_undetermined was run and the below screenshot shows the outputs from each pipeline. (Sorry it is vague on the github)

The left screen is from the previous pipeline which runs multiqc for undetermined fastq files.
THe middle screen is from the current pipeline which doesn't run multiqc for undertermined fastq files.
THe right screen is from the updated pipeline which doesn't run multiqc for undertermined fastq files but runs the cat_fqs_undetermined rule. I tested this with a iseq run. 

I will commit this change to skip_fastqc_multiqc_for_undermined branch. Please let me know if there is anything you would like to comment on. I will start to work on this Barcodes_fraction file. Thank you again for explnation.


<img width="1788" alt="Screen Shot 2021-06-25 at 12 16 20 PM" src="https://user-images.githubusercontent.com/12543093/123455052-40516000-d5af-11eb-9bce-851e93aba010.png">

**Comment by genomics-kl** [comment] 2021-06-25 16:54
@heyyyjude , did you check the Diagnostics folder for the pipeline in your right-most screenshot? It is possible the 'Barcodes_fraction' file is already there.

**Comment by heyyyjude** [comment] 2021-06-25 17:28
@genomics-kl , Yes, you are right. There is that file in the Diagnostics directory. Also, there are symlinks for multiqc html files.

**Comment by genomics-kl** [comment] 2021-06-25 17:46
Ok, great. You can just take the lead from now on and communicate with @VAIgenomics to make sure that everything is how they want it for this and future issues. I'll be available if you want to discuss anything but, in general. I'll let you decide when to merge branches to the main branch etc. My only recommendation is to compare the output files before and after changes/commits to make sure there are no unexpected changes.

**Comment by heyyyjude** [comment] 2021-06-28 19:26
Hello @VAIgenomics 
I have updated the pipeline and tested it with a iseq run. Sorry for the inconvience. The fixed one is available as the below command.

```git clone https://github.com/vari-bbc/demultiplex.git -b skip_fastqc_multiqc_for_undetermined```

Please let me know if you have any errors or trouble using it. Thank you.

**Comment by heyyyjude** [comment] 2021-07-19 13:35
Hi @VAIgenomics ,

Hope all of you had a great weekend. I just would like to know if you have any issues or comments on the updated demux. If you don't have any issues, I would like to merge this updated demux into the master one - so you can just use the master one.

Thanks

**Comment by VAIgenomics** [comment] 2021-07-19 17:39
Hi @heyyyjude ,

I'm sorry but I haven't had any time to test the new pipeline yet. I can check with Marc and see if he has tested it at all.

Becca

**Comment by heyyyjude** [comment] 2021-08-19 20:11
@VAIgenomics 

I updated the master to generate a barcode fraction file and md5sum file. Let me if you have any comments or issues. I will close this issue.

**Closed by heyyyjude** 2021-08-19 20:11 UTC
